apiVersion: cache.tc/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: technical-challenge
  name: redis-sample
spec:
  image: "bitnami/redis"
  version: "latest"
  storage:
    size: "1Gi"
    storageClassName: "standard"
  replicas: 5
  secretName: "redis-key"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "1Gi"
